print(7 and 5)
print(True and True)
print(True and False or True)
print(False or False and True)
print(False or 0)
print(not (False) and True)
print(not(True or not(False and False)))
print((10 > 14) and ( 4 == 5))
print(True and 5)
print((3*4)!=(14-2)or('c'>='d'))
print((12*2)==(3*8))
print((14*2)!=(3*8))
